import { useState } from 'react'

function GardenDetailView({ plot, occupied, onClose, onReserve }) {
  const [sent, setSent] = useState(false)
  return <div className="garden-detail-overlay" role="dialog" aria-modal="true" aria-label="Chi tiết ô đất">
    <header className="detail-topbar"><button className="detail-back" type="button" onClick={onClose}>← Danh sách ô đất</button></header>
    <main className="garden-detail-main"><section className="detail-main-column"><div className="detail-heading"><h1>{plot.area}m² garden plot for lease · {plot.location} [{plot.code}]</h1><p><span className={occupied ? 'detail-status occupied' : 'detail-status'} /> {occupied ? 'Đã thuê' : 'Đang trống'} <b>|</b> {plot.soil}</p></div><div className="detail-gallery"><div className="detail-map-image"><span className="parcel-outline">{plot.code}</span></div></div><div className="detail-facts"><div><small>Diện tích</small><strong>{plot.area}m²</strong></div><div><small>Khu vực</small><strong>{plot.location}</strong></div><div><small>Chăm sóc</small><strong>Đã bao gồm</strong></div><div><small>Mã ô đất</small><strong>{plot.code}</strong></div></div><section className="detail-description"><h2>Mô tả khu vườn</h2><p>{plot.description || 'Ô đất được chuẩn bị sẵn và chăm sóc bởi đội ngũ PlotFarm trong suốt mùa vụ.'}</p></section></section><aside className="detail-sidebar"><div className="detail-price-card"><div className="detail-price"><strong>{occupied ? 'Đã thuê' : `${plot.price.toLocaleString('vi-VN')}đ`}</strong>{!occupied && <small>/ tháng</small>}</div><p>Chi phí chăm sóc đã bao gồm</p><div className="bid-stats"><div><small>Ô đất đang chọn</small><strong>{plot.code}</strong></div><div><small>Thời hạn tối thiểu</small><strong>3 tháng</strong></div></div><button className="detail-primary" type="button" disabled={occupied} onClick={onReserve}>{occupied ? 'Ô đất đã được thuê' : 'Giữ ô đất này'}</button></div><div className="specialist-card"><h2>Liên hệ tư vấn</h2>{sent ? <p className="sent-message">Tin nhắn đã được gửi.</p> : <form onSubmit={(event) => { event.preventDefault(); setSent(true) }}><input required placeholder="Họ và tên" /><input required type="email" placeholder="Địa chỉ email" /><textarea required placeholder="Tôi quan tâm đến ô đất này" /><button type="submit">Gửi tin nhắn</button></form>}</div></aside></main>
  </div>
}

export default GardenDetailView
