import { useState } from 'react'

function GardenDetailView({ plot, occupied, onClose, onReserve }) {
  const [sent, setSent] = useState(false)
  const title = `${plot === 'B-07' ? '24' : '24'}m² garden plot for lease · Vườn Phúc Lộc [${plot}]`

  return <div className="garden-detail-overlay" role="dialog" aria-modal="true" aria-label="Chi tiết ô đất">
    <header className="detail-topbar"><button className="detail-back" type="button" onClick={onClose}>← Danh sách ô đất</button><div className="detail-actions"><button type="button">♡ Lưu</button><button type="button">⌯ Chia sẻ</button></div></header>
    <main className="garden-detail-main">
      <section className="detail-main-column"><div className="detail-heading"><h1>{title}</h1><p><span className={occupied ? 'detail-status occupied' : 'detail-status'} /> {occupied ? 'Đã thuê' : 'Đang trống'} <b>|</b> Vườn rau <b>|</b> Cập nhật hôm nay</p></div><div className="detail-gallery"><div className="detail-map-image"><span className="parcel-outline">{plot}</span><button type="button" className="gallery-arrow left">‹</button><button type="button" className="gallery-arrow right">›</button><div className="detail-map-controls"><button type="button">+</button><button type="button">−</button></div></div><div className="detail-thumbs"><button type="button" className="thumb-active">Bản đồ</button><button type="button">Ảnh vườn</button><img src="https://images.unsplash.com/photo-1501004318641-b39e6451bec6?auto=format&fit=crop&w=180&q=80" alt="Ảnh ô đất" /><img src="https://images.unsplash.com/photo-1464226184884-fa280b87c399?auto=format&fit=crop&w=180&q=80" alt="Ảnh khu vườn" /><img src="https://images.unsplash.com/photo-1492496913980-501348b61469?auto=format&fit=crop&w=180&q=80" alt="Ảnh cây trồng" /></div></div><div className="detail-facts"><div><small>Loại không gian</small><strong>Ô đất trồng rau</strong></div><div><small>Diện tích</small><strong>24m²</strong></div><div><small>Khu vực</small><strong>Vườn Phúc Lộc</strong></div><div><small>Chăm sóc</small><strong>Đã bao gồm</strong></div><div><small>Mã ô đất</small><strong>{plot}</strong></div></div><section className="detail-description"><h2>Mô tả khu vườn <span>⌃</span></h2><div className="detail-tabs"><button className="active" type="button">Mô tả</button><button type="button">Điều khoản mùa vụ</button></div><p><strong>Ô đất {plot} tại Vườn Phúc Lộc</strong> là lựa chọn phù hợp cho những ai muốn bắt đầu trồng rau sạch trong một không gian được chuẩn bị sẵn. Đội ngũ nhà vườn chăm sóc hằng ngày, bạn có thể theo dõi và ghé thăm khu vườn bất cứ lúc nào.</p><button className="read-more" type="button">Đọc thêm</button></section><section className="detail-features"><h2>Tiện ích khu vườn <span>⌃</span></h2><div><span>✓ Nguồn nước sạch</span><span>✓ Đất đã xử lý</span><span>✓ Có chỗ đậu xe</span><span>✓ Hỗ trợ thu hoạch</span></div></section></section>
      <aside className="detail-sidebar"><div className="detail-price-card"><div className="time-left">◷ Đăng ký trong hôm nay để giữ ô đất</div><div className="detail-price"><strong>{occupied ? 'Đã thuê' : '490.000đ'}</strong>{!occupied && <small>/ tháng</small>}</div><p>Chi phí chăm sóc đã bao gồm</p><div className="bid-stats"><div><small>Ô đất đang chọn</small><strong>{plot}</strong></div><div><small>Thời hạn tối thiểu</small><strong>3 tháng</strong></div></div><div className="detail-rows"><div><span>Diện tích</span><b>24m²</b></div><div><span>Loại cây phù hợp</span><b>Rau xanh</b></div><div><span>Ngày bắt đầu</span><b>Trao đổi</b></div><div><span>Tình trạng</span><b>{occupied ? 'Đã thuê' : 'Sẵn sàng'}</b></div></div><button className="detail-primary" type="button" disabled={occupied} onClick={onReserve}>{occupied ? 'Ô đất đã được thuê' : 'Giữ ô đất này'}</button></div><div className="specialist-card"><h2>Chuyên viên khu vườn</h2><div className="specialist-profile"><div className="specialist-avatar">MP</div><div><strong>Minh Phúc</strong><span>PlotFarm Đà Nẵng</span><a href="tel:0900000000">+84 900 000 000</a></div></div><h3>Liên hệ tư vấn</h3>{sent ? <p className="sent-message">Tin nhắn đã được gửi. Chúng mình sẽ liên hệ sớm.</p> : <form onSubmit={(event) => { event.preventDefault(); setSent(true) }}><input required placeholder="Họ và tên" /><input required type="email" placeholder="Địa chỉ email" /><textarea required placeholder="Tôi quan tâm đến ô đất này" /><button type="submit">Gửi tin nhắn</button></form>}</div></aside>
    </main>
  </div>
}

export default GardenDetailView
