import { occupiedPlots, plots } from '../data/plots.js'
import { useState } from 'react'
import GardenMapView from './GardenMapView.jsx'
import GardenDetailView from './GardenDetailView.jsx'

function PlotSelector({ selectedPlot, onSelectPlot, onReserve }) {
  const [showMap, setShowMap] = useState(false)
  const [detailPlot, setDetailPlot] = useState(null)
  return <><section className="plots-section section-shell" id="plots"><div className="section-intro"><div><p className="eyebrow">Ô ĐẤT ĐANG SẴN SÀNG</p><h2>Chọn một không gian<br /><em>cho mùa xanh mới.</em></h2></div><button className="outline-button map-view-button" onClick={() => setShowMap(true)}>⌖ Bản đồ khu vườn</button></div><p className="section-note listings-note">Tạo một khởi đầu mới với ô đất riêng, được chăm sóc và cập nhật minh bạch trong suốt mùa vụ.</p><div className="listing-grid">{plots.slice(0, 3).map((plot, index) => <article className="listing-card" key={plot}><div className={`listing-image listing-image-${index + 1}`}><span className="listing-status"><i /> Đang trống</span><span className="listing-heart">♡</span></div><div className="listing-body"><div className="listing-price"><strong>{index === 0 ? '490.000đ' : index === 1 ? '650.000đ' : '820.000đ'}</strong><small>/ tháng</small></div><p>Vườn Phúc Lộc, Đà Nẵng</p><div className="listing-meta"><span>{plot} · 24m²</span><span>● Có chăm sóc</span></div><button className="listing-select" onClick={() => { onSelectPlot(plot); setDetailPlot(plot) }}>Xem chi tiết <span>→</span></button></div></article>)}</div><div className="listing-banner"><div><p className="eyebrow">MÙA VỤ CỦA BẠN</p><h3>Giữ chỗ cho một mùa xanh</h3><p>Chọn ô đất phù hợp và để đội ngũ PlotFarm đồng hành cùng bạn.</p></div><button className="primary-button" onClick={onReserve}>Giữ ô đất {selectedPlot} <span>→</span></button></div><div className="plot-data" aria-hidden="true">{occupiedPlots.length + plots.length}</div></section>{showMap && <GardenMapView plots={plots} occupiedPlots={occupiedPlots} onSelectPlot={(plot) => { onSelectPlot(plot); setShowMap(false); setDetailPlot(plot) }} onClose={() => setShowMap(false)} />}{detailPlot && <GardenDetailView plot={detailPlot} occupied={occupiedPlots.includes(detailPlot)} onClose={() => setDetailPlot(null)} onReserve={onReserve} />}</>
}
export default PlotSelector
